version: "3.5"

services:
  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - /var/lib/mysql
      - ./docker/myconf:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - /sessions
    ports:
      - ${PHPMYADMIN_PORT:-80}:80
    depends_on:
      - mysql
