version: "3.5"

services:
  jdk:
    image: maven:3.6.3-jdk-13
    volumes:
      - .:/app
      - ./repository:/root/.m2/repository
    working_dir: /app

  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - /var/lib/mysql
      - ./docker/myconf:/etc/mysql/conf.d
    ports:
    - ${MYSQL_PORT:-3306}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - /sessions
    ports:
      - ${PHPMYADMIN_PORT:-80}:80
    depends_on:
      - mysql
